services:
  - type: web
    name: archway-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommandweb: uvicorn backend.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
